### ISSUE TITLE
Some tiles are returning 503 service unavailable

### ISSUE THREAD

**Issue by mbartlett21** [stamen/watercolor#3]
For example

- http://stamen-tiles-b.a.ssl.fastly.net/watercolor/13/7559/4766.jpg
- http://stamen-tiles-a.a.ssl.fastly.net/watercolor/13/7557/4767.jpg

**Comment by almereyda** [comment]
This can probably be closed.

Watercolor is now served from Stadia Maps or from the Cooper Hewitt Collection.

- [Stamen Watercolor - Stadia Maps Documentation](https://docs.stadiamaps.com/map-styles/stamen-watercolor/)
- [Watercolor Maptiles Website Enters Permanent Collection of Cooper Hewitt | Cooper Hewitt, Smithsonian Design Museum](https://www.cooperhewitt.org/2021/05/18/watercolor-maptiles-website-enters-permanent-collection-of-cooper-hewitt/)
  - [Watercolor Map | watercolormaps.collection.cooperhewitt.org](https://watercolormaps.collection.cooperhewitt.org/)
  - [CooperHewittCollection/watercolor](https://github.com/CooperHewittCollection/watercolor)
  - [CooperHewittCollection/watercolor_examples: Examples to use Stamen's Watercolor Maptiles for Leaflet, OpenLayers and MapLibre libraries via Smithsonian/ Cooper Hewitt](https://github.com/CooperHewittCollection/watercolor_examples)

**Comment by almccon** [comment]
Correct @almereyda, thanks for this comment! Yes, this ticket is no longer relevant.
